import { array } from 'modern-fns';
import { fn, json, num, pick, type DemoModule } from './types';

const USERS = `[
  { "id": 1, "name": "Ann", "role": "admin", "age": 30 },
  { "id": 2, "name": "Bob", "role": "editor", "age": 25 },
  { "id": 3, "name": "Cid", "role": "admin", "age": 25 }
]`;

export const arrayModule: DemoModule = {
  module: 'array',
  blurb: 'Immutable list transforms. Every selector accepts a key name or a function.',
  specs: [
    {
      name: 'chunk',
      signature: 'chunk<T>(array: readonly T[], size: number): T[][]',
      summary: 'Split into consecutive groups; the last group holds the remainder.',
      inputs: [json('array', '[1, 2, 3, 4, 5]'), num('size', '2')],
      run: array.chunk,
    },
    {
      name: 'unique',
      signature: 'unique<T>(array: readonly T[]): T[]',
      summary: 'Drop duplicates, keeping first occurrence. NaN de-duplicates correctly.',
      inputs: [json('array', '[3, 1, 3, 2, 1]')],
      run: array.unique,
    },
    {
      name: 'uniqueBy',
      signature: 'uniqueBy<T>(array, selector): T[]',
      summary: 'Drop duplicates by a derived key.',
      inputs: [json('array', USERS, 5), fn('selector', '(u) => u.role')],
      run: array.uniqueBy,
    },
    {
      name: 'groupBy',
      signature: 'groupBy<T>(array, selector): Record<string, T[]>',
      summary: 'Group items by property name or derived key.',
      inputs: [json('array', USERS, 5), pick('selector', 'role', ['role', 'age', 'name'])],
      run: array.groupBy,
    },
    {
      name: 'indexBy',
      signature: 'indexBy<T>(array, selector): Record<string, T>',
      summary: 'Lookup table keyed by a property; last duplicate wins.',
      inputs: [json('array', USERS, 5), pick('selector', 'id', ['id', 'role', 'name'])],
      run: array.indexBy,
    },
    {
      name: 'partition',
      signature: 'partition<T>(array, predicate): [T[], T[]]',
      summary: 'Split into [matching, notMatching] in one pass.',
      inputs: [json('array', '[1, 2, 3, 4, 5, 6]'), fn('predicate', '(n) => n % 2 === 0')],
      run: array.partition,
    },
    {
      name: 'sortBy',
      signature: 'sortBy<T>(array, selector): T[]',
      summary: 'Stable ascending sort that returns a new array. Nullish keys sort last.',
      inputs: [json('array', USERS, 5), fn('selector', '(u) => u.age')],
      run: array.sortBy,
    },
    {
      name: 'orderBy',
      signature: 'orderBy<T>(array, selectors, directions?): T[]',
      summary: 'Multi-key sort with independent directions.',
      inputs: [
        json('array', USERS, 5),
        fn('selectors', '["role", "age"]'),
        json('directions', '["asc", "desc"]'),
      ],
      run: array.orderBy,
    },
    {
      name: 'compareValues',
      signature: 'compareValues(a: unknown, b: unknown): number',
      summary: 'The comparator behind sortBy: nullish last, NaN last, locale-aware strings.',
      inputs: [json('a', '"apple"'), json('b', 'null')],
      run: array.compareValues,
      note: 'Exposed for building your own comparators.',
    },
    {
      name: 'flatten',
      signature: 'flatten<T>(array): T[]',
      summary: 'Flatten exactly one level.',
      inputs: [json('array', '[1, [2, 3], [[4]]]')],
      run: array.flatten,
    },
    {
      name: 'flattenDeep',
      signature: 'flattenDeep<T>(array): T[]',
      summary: 'Flatten every level, iteratively — no stack overflow on deep input.',
      inputs: [json('array', '[1, [2, [3, [4, [5]]]]]')],
      run: array.flattenDeep,
    },
    {
      name: 'compact',
      signature: 'compact<T>(array): T[]',
      summary: 'Remove every falsy value, narrowing the type.',
      inputs: [json('array', '[0, 1, false, 2, "", 3, null]')],
      run: array.compact,
    },
    {
      name: 'difference',
      signature: 'difference<T>(array, other, selector?): T[]',
      summary: 'Values in the first array only. Pass a selector to compare objects by key.',
      inputs: [json('array', '[1, 2, 3]'), json('other', '[2]')],
      run: array.difference,
    },
    {
      name: 'intersection',
      signature: 'intersection<T>(array, other, selector?): T[]',
      summary: 'Values present in both, de-duplicated, in first-array order.',
      inputs: [json('array', '[1, 2, 2, 3]'), json('other', '[2, 3, 4]')],
      run: array.intersection,
    },
    {
      name: 'union',
      signature: 'union<T>(...arrays): T[]',
      summary: 'Concatenate and de-duplicate, keeping first-seen order.',
      inputs: [json('a', '[1, 2]'), json('b', '[2, 3]'), json('c', '[3, 4]')],
      run: array.union,
    },
    {
      name: 'zip',
      signature: 'zip(...arrays): Zipped[]',
      summary: 'Combine position-wise, padding to the longest input.',
      inputs: [json('a', '[1, 2, 3]'), json('b', '["a", "b"]')],
      run: array.zip,
    },
    {
      name: 'unzip',
      signature: 'unzip<T>(array): T[][]',
      summary: 'Rows to columns — the inverse of zip.',
      inputs: [json('rows', '[[1, "a"], [2, "b"]]')],
      run: array.unzip,
    },
    {
      name: 'first',
      signature: 'first<T>(array): T | undefined',
      summary: 'First element (array-only version).',
      inputs: [json('array', '[10, 20, 30]')],
      run: array.first,
    },
    {
      name: 'last',
      signature: 'last<T>(array): T | undefined',
      summary: 'Last element (array-only version).',
      inputs: [json('array', '[10, 20, 30]')],
      run: array.last,
    },
    {
      name: 'take',
      signature: 'take<T>(array, count?): T[]',
      summary: 'First n elements; counts are clamped.',
      inputs: [json('array', '[1, 2, 3, 4]'), num('count', '2')],
      run: array.take,
    },
    {
      name: 'takeRight',
      signature: 'takeRight<T>(array, count?): T[]',
      summary: 'Last n elements, in original order.',
      inputs: [json('array', '[1, 2, 3, 4]'), num('count', '2')],
      run: array.takeRight,
    },
    {
      name: 'drop',
      signature: 'drop<T>(array, count?): T[]',
      summary: 'Everything after the first n.',
      inputs: [json('array', '[1, 2, 3, 4]'), num('count', '1')],
      run: array.drop,
    },
    {
      name: 'dropRight',
      signature: 'dropRight<T>(array, count?): T[]',
      summary: 'Everything except the last n.',
      inputs: [json('array', '[1, 2, 3, 4]'), num('count', '1')],
      run: array.dropRight,
    },
    {
      name: 'range',
      signature: 'range(start, end?, step?): number[]',
      summary: 'End-exclusive numeric range. Impossible ranges give [] instead of hanging.',
      inputs: [num('start', '0'), num('end', '10'), num('step', '2.5')],
      run: array.range,
    },
    {
      name: 'window',
      signature: 'window<T>(array, size): T[][]',
      summary: 'Sliding windows of consecutive items, step 1.',
      inputs: [json('array', '[1, 2, 3, 4]'), num('size', '2')],
      run: array.window,
    },
    {
      name: 'slidingWindow',
      signature: 'slidingWindow<T>(array, size): T[][]',
      summary: 'Alias of window — use it in browser code so the DOM global is not shadowed.',
      inputs: [json('array', '[1, 2, 3, 4, 5]'), num('size', '3')],
      run: array.slidingWindow,
    },
    {
      name: 'diffArray',
      signature: 'diffArray<T>(oldArray, newArray, key?, options?): ArrayDiff<T>',
      summary: 'List reconciliation: added, removed, updated (with field changes), unchanged.',
      inputs: [
        json('oldArray', '[{ "id": 1, "name": "John" }, { "id": 2, "name": "Bob" }]', 3),
        json('newArray', '[{ "id": 1, "name": "Vishnu" }, { "id": 3, "name": "Dee" }]', 3),
        json('key', '"id"'),
        json('options', '{ "withChanges": true }'),
      ],
      run: array.diffArray,
    },
  ],
};
