import { number } from 'modern-fns';
import { json, num, pick, text, type DemoModule } from './types';

export const numberModule: DemoModule = {
  module: 'number',
  blurb: 'Decimal-safe maths, business maths and Intl formatting with safe fallbacks.',
  specs: [
    {
      name: 'clamp',
      signature: 'clamp(value, min, max): number',
      summary: 'Constrain to a range; swapped bounds are normalised.',
      inputs: [num('value', '150'), num('min', '0'), num('max', '100')],
      run: number.clamp,
    },
    {
      name: 'round',
      signature: 'round(value, decimals?): number',
      summary: 'Decimal-safe: round(1.005, 2) is 1.01, where Math.round gives 1.',
      inputs: [num('value', '1.005'), num('decimals', '2')],
      run: number.round,
    },
    {
      name: 'floor',
      signature: 'floor(value, decimals?): number',
      summary: 'Decimal-safe Math.floor.',
      inputs: [num('value', '1.999'), num('decimals', '2')],
      run: number.floor,
    },
    {
      name: 'ceil',
      signature: 'ceil(value, decimals?): number',
      summary: 'Decimal-safe Math.ceil.',
      inputs: [num('value', '1.001'), num('decimals', '2')],
      run: number.ceil,
    },
    {
      name: 'percentage',
      signature: 'percentage(value, total, decimals?): number',
      summary: 'A zero total gives 0, not NaN.',
      inputs: [num('value', '25'), num('total', '200'), num('decimals', '')],
      run: number.percentage,
    },
    {
      name: 'percentageChange',
      signature: 'percentageChange(oldValue, newValue): number',
      summary: 'Growth from zero is Infinity — check with Number.isFinite.',
      inputs: [num('oldValue', '200'), num('newValue', '250')],
      run: number.percentageChange,
    },
    {
      name: 'formatNumber',
      signature: 'formatNumber(value, options?): string',
      summary: 'Intl formatting with a fallback for null / NaN / unparseable input.',
      inputs: [
        json('value', '1234567.891'),
        json('options', '{ "locale": "en-IN", "decimals": 2 }'),
      ],
      run: number.formatNumber,
    },
    {
      name: 'abbreviate',
      signature: 'abbreviate(value, options?): string',
      summary: 'Locale-independent compaction; rounds toward zero so counts never overstate.',
      inputs: [num('value', '1500000'), json('options', '{ "decimals": 1 }')],
      run: number.abbreviate,
    },
    {
      name: 'currency',
      signature: 'currency(value, currency, locale?, options?): string',
      summary: 'Money with the right symbol and grouping; invalid codes fall back.',
      inputs: [
        num('value', '1299.5'),
        pick('currency', 'INR', ['INR', 'USD', 'EUR', 'JPY', 'GBP']),
        pick('locale', 'en-IN', ['en-IN', 'en-US', 'de-DE', 'ja-JP']),
      ],
      run: number.currency,
    },
    {
      name: 'random',
      signature: 'random(min?, max?, options?): number',
      summary: 'Inclusive at both ends for integers. Injectable source for tests.',
      inputs: [num('min', '1'), num('max', '6')],
      run: number.random,
      widget: 'random',
    },
    {
      name: 'range',
      signature: 'range(start, end?, step?): number[]',
      summary: 'The same function as array/range, re-exported.',
      inputs: [num('start', '1'), num('end', '5'), num('step', '')],
      run: number.range,
    },
    {
      name: 'isNumeric',
      signature: 'isNumeric(value: unknown): boolean',
      summary: 'Rejects "", null and [] — everything Number() silently coerces to 0.',
      inputs: [json('value', '"42"')],
      run: number.isNumeric,
    },
    {
      name: 'toNumber',
      signature: 'toNumber(value, defaultValue?): number',
      summary: 'Parses currency symbols and thousands separators. Same as value/toNumber.',
      inputs: [text('value', '₹1,299.50'), json('defaultValue', '0')],
      run: number.toNumber,
    },
    {
      name: 'tax',
      signature: 'tax(value, percentage, decimals?): number',
      summary: 'Returns the gross amount. Subtract the input for the tax component.',
      inputs: [num('value', '1000'), num('percentage', '18'), num('decimals', '2')],
      run: number.tax,
    },
    {
      name: 'discount',
      signature: 'discount(value, percentage, decimals?): number',
      summary: 'Returns the net amount, clamped at 0 for positive inputs.',
      inputs: [num('value', '1000'), num('percentage', '10'), num('decimals', '2')],
      run: number.discount,
    },
    {
      name: 'compoundInterest',
      signature: 'compoundInterest(principal, rate, periods, years, decimals?): number',
      summary: 'Final amount P(1 + r/n)^(nt); rate is a percentage.',
      inputs: [
        num('principal', '100000'),
        num('rate', '7.5'),
        num('periods', '12'),
        num('years', '10'),
      ],
      run: number.compoundInterest,
    },
  ],
};
