import { string } from 'modern-fns';
import { json, num, text, type DemoModule } from './types';

export const stringModule: DemoModule = {
  module: 'string',
  blurb: 'Unicode-aware text utilities. Non-strings return "" instead of throwing.',
  specs: [
    {
      name: 'capitalize',
      signature: 'capitalize(value: string): string',
      summary: 'Upper-case the first code point, safe on emoji and empty strings.',
      inputs: [text('value', 'hello world')],
      run: string.capitalize,
    },
    {
      name: 'capitalizeWords',
      signature: 'capitalizeWords(value: string): string',
      summary: 'Capitalise each word, preserving the original spacing.',
      inputs: [text('value', 'hello vue world')],
      run: string.capitalizeWords,
    },
    {
      name: 'camelCase',
      signature: 'camelCase(value: string): string',
      summary: 'Any casing to camelCase.',
      inputs: [text('value', 'user_first_name')],
      run: string.camelCase,
    },
    {
      name: 'pascalCase',
      signature: 'pascalCase(value: string): string',
      summary: 'Any casing to PascalCase.',
      inputs: [text('value', 'my-component')],
      run: string.pascalCase,
    },
    {
      name: 'kebabCase',
      signature: 'kebabCase(value: string): string',
      summary: 'Any casing to kebab-case. Acronyms split correctly.',
      inputs: [text('value', 'XMLHttpRequest')],
      run: string.kebabCase,
    },
    {
      name: 'snakeCase',
      signature: 'snakeCase(value: string): string',
      summary: 'Any casing to snake_case.',
      inputs: [text('value', 'userFirstName')],
      run: string.snakeCase,
    },
    {
      name: 'constantCase',
      signature: 'constantCase(value: string): string',
      summary: 'Any casing to CONSTANT_CASE.',
      inputs: [text('value', 'userFirstName')],
      run: string.constantCase,
    },
    {
      name: 'slugify',
      signature: 'slugify(value, options?): string',
      summary: 'URL-safe slug: folds diacritics, & becomes and, punctuation dropped.',
      inputs: [text('value', 'Café & Bar — 2026'), json('options', '{ "separator": "-" }')],
      run: string.slugify,
    },
    {
      name: 'truncate',
      signature: 'truncate(value, length, options?): string',
      summary: 'Length includes the omission, so the result never exceeds your budget.',
      inputs: [
        text('value', 'The quick brown fox'),
        num('length', '10'),
        json('options', '{ "omission": "…" }'),
      ],
      run: string.truncate,
    },
    {
      name: 'truncateWords',
      signature: 'truncateWords(value, wordCount, options?): string',
      summary: 'Keep the first n words — the natural choice for previews.',
      inputs: [
        text('value', 'The quick brown fox jumps'),
        num('wordCount', '3'),
        json('options', '{}'),
      ],
      run: string.truncateWords,
    },
    {
      name: 'initials',
      signature: 'initials(value, options?): string',
      summary: 'Avatar initials: first and last parts, skipping middle names.',
      inputs: [text('value', 'john ronald reuel tolkien'), json('options', '{ "max": 2 }')],
      run: string.initials,
    },
    {
      name: 'mask',
      signature: 'mask(value, options?): string',
      summary: 'Mask all but the visible tail. Short values are fully masked.',
      inputs: [text('value', '9876543210'), json('options', '{ "visible": 4 }')],
      run: string.mask,
    },
    {
      name: 'stripHtml',
      signature: 'stripHtml(value: string): string',
      summary: 'Remove tags; script and style blocks go with their contents. Not a sanitiser.',
      inputs: [text('value', '<p>Hello <b>world</b></p><script>alert(1)</script>')],
      run: string.stripHtml,
    },
    {
      name: 'stripWhitespace',
      signature: 'stripWhitespace(value: string): string',
      summary: 'Remove every unicode whitespace character.',
      inputs: [text('value', ' 4111 1111 1111 1111 ')],
      run: string.stripWhitespace,
    },
    {
      name: 'removeSpaces',
      signature: 'removeSpaces(value: string): string',
      summary: 'Remove ASCII spaces only, keeping tabs and newlines.',
      inputs: [text('value', 'a b c')],
      run: string.removeSpaces,
    },
    {
      name: 'normalizeWhitespace',
      signature: 'normalizeWhitespace(value: string): string',
      summary: 'Collapse whitespace runs to one space and trim.',
      inputs: [text('value', '  Hello \t world  ')],
      run: string.normalizeWhitespace,
    },
    {
      name: 'escapeHtml',
      signature: 'escapeHtml(value: string): string',
      summary: 'Escape the five characters that break HTML markup.',
      inputs: [text('value', '<script>alert("x")</script>')],
      run: string.escapeHtml,
    },
    {
      name: 'unescapeHtml',
      signature: 'unescapeHtml(value: string): string',
      summary: 'Reverse escapeHtml and decode numeric entities.',
      inputs: [text('value', 'caf&#233; &lt;b&gt;hi&lt;/b&gt;')],
      run: string.unescapeHtml,
    },
    {
      name: 'isEmail',
      signature: 'isEmail(value: unknown): boolean',
      summary: 'Pragmatic validation: plus-addressing yes, missing TLD no.',
      inputs: [text('value', 'vishnu+tag@example.co.in')],
      run: string.isEmail,
    },
    {
      name: 'isUrl',
      signature: 'isUrl(value, options?): boolean',
      summary: 'Uses the URL parser. http(s) only by default, so javascript: is rejected.',
      inputs: [
        text('value', 'https://example.com/path?q=1'),
        json('options', '{ "protocols": ["http", "https"] }'),
      ],
      run: string.isUrl,
    },
    {
      name: 'extractNumbers',
      signature: 'extractNumbers(value: string): number[]',
      summary: 'Pull numbers out of free text, including grouped and negative values.',
      inputs: [text('value', 'Order #123 total 1,299.50, -5 items')],
      run: string.extractNumbers,
    },
    {
      name: 'extractEmails',
      signature: 'extractEmails(value: string): string[]',
      summary: 'Pull addresses out of free text, lower-cased and de-duplicated.',
      inputs: [text('value', 'Mail a@x.com or B@X.COM, also a@x.com')],
      run: string.extractEmails,
    },
  ],
};
